############# English navigation ##############

# main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
# parent = "About"
name = "History"
url = "/history"
weight = 3

[[main]]
# parent = "About"
name = "What is Evangelicalism?"
url = "/evangelicalism"
weight = 1

[[main]]
name = "Beliefs"
url = "/beliefs"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6

# [[main]]
# weight = 4
# name = "Pages"

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Elements"
url = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
